version: v1

labels:
  - label: 'Scope: meta'
    sync: true
    matcher:
      files: [".github/**"]
  - label: 'Scope: Game client'
    sync: true
    matcher:
      files: ["js/**"]
  - label: 'Scope: game server'
    sync: true
    matcher:
      files: ["node/**"]